// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrmJupeWtMnan0euE6nhbQIZvk20_Qz0',
    appId: '1:577432885834:web:87acb0bfce45b207cbe4b3',
    messagingSenderId: '577432885834',
    projectId: 'quiz-2059e',
    authDomain: 'quiz-2059e.firebaseapp.com',
    storageBucket: 'quiz-2059e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxsiQFk0OyXg0U44yJDT-XkMLHtQpADs',
    appId: '1:577432885834:android:97544e530f2f9132cbe4b3',
    messagingSenderId: '577432885834',
    projectId: 'quiz-2059e',
    storageBucket: 'quiz-2059e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tfRq0Xbeng8n8CnjG1u9t5iT3Q96D3Q',
    appId: '1:577432885834:ios:a2a237e655c167fecbe4b3',
    messagingSenderId: '577432885834',
    projectId: 'quiz-2059e',
    storageBucket: 'quiz-2059e.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0tfRq0Xbeng8n8CnjG1u9t5iT3Q96D3Q',
    appId: '1:577432885834:ios:2fffe9cdd09e77c3cbe4b3',
    messagingSenderId: '577432885834',
    projectId: 'quiz-2059e',
    storageBucket: 'quiz-2059e.appspot.com',
    iosBundleId: 'com.example.quiz.RunnerTests',
  );
}
